version: "3"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      # - ./src:/app
      - ./env:/env
      #  - ./log:/app/log
    container_name: yunbankeCheckIn_app
    networks:
      - yunbankeCheckIn

networks:
  yunbankeCheckIn: